{ "records":[ {"Name":"Rincy Banu","City":"Zurich"},
{"Name":"Manoj R","City":"México D.F."},
{"Name":"Pooja Sharma","City":"Bangalore"},
{"Name":"Ranjana Patil","City":"Bern"},
{"Name":"Syed Mudasir","City":"London"},
{"Name":"Niranjan","City":"Mysore"},
{"Name":"Bindu","City":"Mannheim"},
{"Name":"Santhosh yadhav","City":"Seattle"},
{"Name":"Prajwal Gowda","City":"Mumbai"},
{"Name":"Nageshwar","City":"Marseill"},
{"Name":"Rakshith","City":"Tsawassen"} ] } 